apiVersion: v1
kind: Service
metadata:
  name: redis-external-service
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - name: redis-external-port
    protocol: TCP
    port: 6379
    nodePort: 30001
  - name: redis-web-port
    protocol: TCP
    port: 8081
    nodePort: 30002

---
apiVersion: v1
kind: Service
metadata:
  name: mq-external-service
spec:
  type: NodePort
  selector:
    app: mq
  ports:
  - name: mq-web-port
    protocol: TCP
    port: 15672
    nodePort: 30003
