# syntax=docker/dockerfile:1
FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime
WORKDIR /code

# import cv2
# ImportError: libGL.so.1: cannot open shared object file: No such file or directory
RUN apt-get update
RUN apt-get install -y libgl1-mesa-dev libglib2.0-0

ENV PYTHONPATH="/code"
COPY ./requirements_torch.txt requirements.txt
RUN pip install -U -r requirements.txt
