# syntax=docker/dockerfile:1
FROM python:3.11.3
WORKDIR /code

# import cv2
# ImportError: libGL.so.1: cannot open shared object file: No such file or directory
RUN apt-get update
RUN apt-get install -y python3-opencv

ENV PYTHONPATH="/code"
COPY ./requirements_latest.txt requirements.txt
RUN pip install -U -r requirements.txt
RUN pip install pytest==7.3.1 black==23.3.0 flake8==6.0.0
