# syntax=docker/dockerfile:1
FROM python:3.11.4
WORKDIR /code

# import cv2
# ImportError: libGL.so.1: cannot open shared object file: No such file or directory
RUN apt-get update
RUN apt-get install -y libgl1-mesa-dev libglib2.0-0

ENV PYTHONPATH="/code"
COPY ./requirements_latest.txt requirements.txt
RUN pip install -U -r requirements.txt
