# syntax=docker/dockerfile:1
FROM python:3.7-slim
WORKDIR /code

# import cv2
# ImportError: libGL.so.1: cannot open shared object file: No such file or directory
RUN apt-get update
RUN apt-get install -y libsm6 libxext6 libxrender-dev libglib2.0-0

ENV PYTHONPATH="/code"
COPY ./requirements_low.txt requirements.txt
RUN pip install -U -r requirements.txt
RUN pip install pytest==7.3.1 black==23.3.0 flake8==6.0.0
