# syntax=docker/dockerfile:1
FROM tensorflow/tensorflow:2.16.1-gpu
WORKDIR /code
ENV PYTHONPATH="/code"

# import cv2
# ImportError: libGL.so.1: cannot open shared object file: No such file or directory
RUN apt update
RUN apt install -y libgl1-mesa-dev libglib2.0-0

COPY ./requirements_latest.txt requirements.txt
RUN pip install tensorflow_probability[tf]==0.24.0
RUN pip install -U -r requirements.txt
