# syntax=docker/dockerfile:1
FROM tensorflow/tensorflow:2.10.1-gpu
WORKDIR /code

# import cv2
# ImportError: libGL.so.1: cannot open shared object file: No such file or directory
RUN apt-get update
RUN apt-get install -y libgl1-mesa-dev libglib2.0-0

ENV PYTHONPATH="/code"
COPY ./requirements_tf210.txt requirements.txt
RUN pip install -U -r requirements.txt
RUN pip install pytest==7.3.1
