version: "3.9"

services:
  srl-latest-tf:
    build:
      dockerfile: ./latest_tf_gpu_dockerfile
    volumes:
      - ../:/code/
    command: /bin/bash
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
