services:
  srl-latest-tf:
    build:
      dockerfile: ./latest_tf_gpu_dockerfile
    volumes:
      - ../:/code/
    command: /bin/bash
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    