services:
  srl-latest-torch:
    build:
      dockerfile: ./latest_torch_gpu_dockerfile
    volumes:
      - ../:/code/
    command: /bin/bash
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    