apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  type: LoadBalancer
  selector:
    app: trainer
  ports:
  - name: redis-external-port
    protocol: TCP
    port: 16379
    targetPort: 6379
  - name: redis-web-port
    protocol: TCP
    port: 18081
    targetPort: 8081
