services:
  srl-tf215-gpu:
    build:
      dockerfile: ./dockerfile_tf215_gpu
    volumes:
      - ../:/code/
    command: /bin/bash
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
