services:
  srl-tf215-gpu:
    build:
      dockerfile: ./tf215_gpu_dockerfile
    volumes:
      - ../../:/code/
    command: /bin/bash
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
