version: "3.9"

services:
  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      #- ./mosquitto/log:/mosquitto/log
