@startuml class_env

enum SpaceTypes {
    DISCRETE
    CONTINUOUS
    GRAY_2ch
    GRAY_3ch
    COLOR
    IMAGE
    TEXT
    MULTI
}

abstract SpaceBase {
    stype : SpaceTypes
    create_encode_space()
    encode_to_space()
    decode_from_space()
}
note as SpaceMemo
- DiscreteSpace
- ArrayDiscreteSpace
- ContinuousSpace
- ArrayContinuousSpace
- BoxSpace
end note
SpaceBase <|-- SpaceMemo

SpaceBase .. SpaceTypes

abstract EnvBase {
    action_space : SpaceBase
    observation_space : SpaceBase
    player_num : int
    next_player: int
    setup()
    reset(seed)
    step(action)
    render_terminal()
    render_rgb_array()
} 

EnvBase .. SpaceBase

abstract gymnasium.Env {}
abstract gym.Env {}
class GymnasiumWrapper {}
class GymWrapper {}

GymnasiumWrapper o-- gymnasium.Env
GymWrapper o-- gym.Env
EnvBase -- GymnasiumWrapper
EnvBase -- GymWrapper

class EnvRun {
    config : EnvConfig
    env : EnvBase
    setup(render_mode)
    reset(seed)
    step(action)
    render()
}
EnvRun -- EnvBase

note "Keeps run-time state." as EnvRunMemo
EnvRun . EnvRunMemo


class EnvConfig {
    name : str
    kwargs : dict
}
EnvRun -- EnvConfig


@enduml