@startuml
autoactivate on

actor Runner
participant Env
participant Players
participant Trainer

activate Runner

Runner -> Env: reset
return state, next_player_indices

Runner -> Players: _set_status("INIT")
return

loop episode

    loop next_player_indices
        alt player status == "INIT"
            Runner -> Players: on_reset
            return
            Runner -> Players: _set_status("RUNNING")
            return
        end

        Runner -> Players: policy
        return action
    end

    Runner -> Env: step(action)
    return next_state, reward, done, next_player_indices, info

    loop next_player_indices
        alt player status == "RUNNING"
            Runner -> Players: on_step(next_state, reward, done)
            return info
        end
    end

    Runner -> Trainer: train
    return info

end
deactivate Runner

@enduml