@startuml
autoactivate on

participant TrainerProcess
participant Trainer
participant Parameter
participant RemoteMemory
entity Board
queue LastParamQueue


activate TrainerProcess
TrainerProcess -> Parameter ** : create
TrainerProcess -> Trainer ** : create
loop wait

    TrainerProcess -> Trainer: train
        Trainer ->> RemoteMemory: sample
        return batchs

        Trainer -> Parameter: update parameter
        return
    return

    TrainerProcess -> Parameter: backup
    return parameter
    TrainerProcess ->> Board: write(parameter)
    return

end

TrainerProcess -> Parameter: backup
return parameter
TrainerProcess ->> LastParamQueue: put(parameter)
return

@enduml