@startuml runner_distributed_flow
autoactivate on

box TrainerServer #Implementation
    participant Trainer
    participant Memory
    participant Parameter
    boundary TrainerIO
end box
box RemoteServer #Technology
    entity RemoteBoard
    queue RemoteQueue
end box
box ActorServers #Application
    participant Actors
end box

note over TrainerIO: Trainer subthread

loop Actor play
    Actors ->> RemoteBoard: read parameter
    return (update actor parameter)
    Actors ->> RemoteQueue: put(batch)
    return
end

par Sync parameter
    TrainerIO -> Parameter: backup
    return parameter
    TrainerIO ->> RemoteBoard: write(parameter)
    return
end

par Add memory
    TrainerIO ->> RemoteQueue: get()
    return batch
    TrainerIO -> Memory: add(batch)
    return
end

loop Trainer train
    Trainer -> Memory: sample()
    return batchs
    Trainer -> Parameter: update parameter
    return
end

@enduml
