@startuml
actor Runner
participant TrainerProcess
participant WorkerProcess
queue LastParamQueue
participant ReplayMemory
entity Board



activate Runner

group create area
    Runner -> ReplayMemory ** : create
    Runner -> Board ** : create
    Runner -> LastParamQueue ** : create Queue

    Runner -> TrainerProcess ** : new process
    loop worker num
        Runner -> WorkerProcess ** : new process
    end
end


hnote over Runner : wait


group end area

    TrainerProcess ->> LastParamQueue: send parameter
    LastParamQueue ->> Runner: recv parameter

    Runner -> WorkerProcess !! : terminate
    Runner -> TrainerProcess !! : terminate
    Runner -> LastParamQueue !! : close
    Runner -> ReplayMemory !!
    Runner -> Board !!

end

deactivate Runner

@enduml
