@startuml
autoactivate on

actor Runner
participant Env
participant Worker
participant Trainer
participant Parameter
participant RemoteMemory


activate Runner

Runner -> Env: reset
return
Runner -> Worker: on_reset
return

loop episode
    Runner -> Worker: policy
        Worker -> Parameter: get parameter
        return parameter
    return action
    Runner -> Env: step(action)
    return next_state, reward, done, info

    Runner -> Worker: on_step(state, action, next_state, reward, done)
        Worker -> RemoteMemory: add batchs
        return
    return info

    Runner -> Trainer: train
        Trainer -> RemoteMemory: sample
        return batchs

        Trainer -> Parameter: update parameter
        return
    return info

end
deactivate Runner

@enduml